### ISSUE TITLE
Merge in hosting-platform Dockerfile best practices?

### ISSUE THREAD

**Issue by sublimino** [UKHomeOffice/technical-service-requirements#12]
Should https://github.com/UKHomeOffice/hosting-platform/blob/master/developer-docs/writing_dockerfiles.md be merged into this repo?

**Comment by timgent** [comment]
@sublimino maybe we should just link to it? PRs welcome :)

**Comment by sublimino** [comment]
Addressed in https://github.com/UKHomeOffice/technical-service-requirements/pull/13
